### PR TITLE
Update CMakeLists.txt to enable building on macOS

### PR DESCRIPTION
**Pull request by gingerbeardman**
See https://github.com/xavery/dcue/issues/14#issuecomment-1666556379

### CODE REVIEW

**Comment by lighterowl** [comment]
Thanks. You should still build with `CMAKE_BUILD_TYPE` defined to one of the standard options though, i.e. `Debug`, `Release`, `MinSizeRel` or `RelWithDebInfo` as this will result in the proper optimisation flags being passed to the compiler.

**Comment by gingerbeardman** [comment]
I had no idea about those! I must have missed that info, if it's in the readme?

I have just rebuilt as `Release`, thanks.

**Comment by lighterowl** [comment]
That's a standard CMake variable, I was actually surprised to learn that it might not be defined at all as I had always assumed CMake sets it automagically to `Debug` if it's not defined explicitly, but it appears not to be the case - otherwise you wouldn't have gotten this error at all.

Read all about it here : https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html

It actually says the default is an empty string which explains why the `if` errored out for you. I think I've made a habit out of setting it and simply always launch `cmake` with `-DCMAKE_BUILD_TYPE=Foobar`.

**Comment by gingerbeardman** [comment]
Well we've both learned something today! Cheers

**Pull request merged**
